from __future__ import annotations

from collections import defaultdict
from statistics import mean

from .models import Stock, StockSnapshot


def risk_score(history: list[float], snapshot: StockSnapshot) -> int:
    """
    Calculate the risk score for a given stock snapshot.

    The risk score is calculated based on the stock's price history, 
    daily move, and volume pressure.

    Args:
    history (list[float]): The stock's price history.
    snapshot (StockSnapshot): The current stock snapshot.

    Returns:
    int: The risk score, ranging from 0 to 100.
    """
    returns = []
    for previous, current in zip(history, history[1:]):
        if previous:
            returns.append(abs((current - previous) / previous) * 100)
    volatility = mean(returns) if returns else 0
    daily_move = abs(snapshot.change_percent)
    volume_pressure = max(0, snapshot.volume_change_percent) / 10
    score = round(volatility * 12 + daily_move * 9 + volume_pressure)
    return max(0, min(100, score))


def risk_label(score: int) -> str:
    """
    Determine the risk label based on the risk score.

    Args:
    score (int): The risk score.

    Returns:
    str: The risk label, either "Low", "Medium", or "High".
    """
    if score >= 70:
        return "High"
    if score >= 40:
        return "Medium"
    return "Low"


def market_breadth(snapshots: list[StockSnapshot]) -> dict[str, int]:
    """
    Calculate the market breadth.

    The market breadth is calculated by counting the number of gainers, losers, and flat stocks.

    Args:
    snapshots (list[StockSnapshot]): The list of stock snapshots.

    Returns:
    dict[str, int]: A dictionary containing the number of gainers, losers, and flat stocks.
    """
    gainers = sum(1 for item in snapshots if item.change_percent > 0)
    losers = sum(1 for item in snapshots if item.change_percent < 0)
    flat = len(snapshots) - gainers - losers
    return {"gainers": gainers, "losers": losers, "flat": flat}


def top_movers(snapshots: list[StockSnapshot], limit: int = 5) -> dict[str, list[StockSnapshot]]:
    """
    Determine the top movers.

    The top movers are determined by sorting the stock snapshots by their change percent and volume change percent.

    Args:
    snapshots (list[StockSnapshot]): The list of stock snapshots.
    limit (int): The number of top movers to return. Defaults to 5.

    Returns:
    dict[str, list[StockSnapshot]]: A dictionary containing the top gainers, losers, and volume movers.
    """
    return {
        "gainers": sorted(snapshots, key=lambda item: item.change_percent, reverse=True)[:limit],
        "losers": sorted(snapshots, key=lambda item: item.change_percent)[:limit],
        "volume": sorted(snapshots, key=lambda item: item.volume_change_percent, reverse=True)[:limit],
    }


def sector_heatmap(stocks: list[Stock], snapshots: list[StockSnapshot]) -> list[dict[str, object]]:
    """
    Generate a sector heatmap.

    The sector heatmap is generated by grouping the stock snapshots by their sector and calculating the average change percent.

    Args:
    stocks (list[Stock]): The list of stocks.
    snapshots (list[StockSnapshot]): The list of stock snapshots.

    Returns:
    list[dict[str, object]]: A list of dictionaries containing the sector and average change percent.
    """
    by_symbol = {item.symbol: item for item in stocks}
    groups: dict[str, list[StockSnapshot]] = defaultdict(list)
    for snapshot in snapshots:
        stock = by_symbol.get(snapshot.symbol)
        if stock:
            groups[stock.sector].append(snapshot)
    heatmap = []
    for sector, items in groups.items():
        average_change = mean([item.change_percent for item in items])
        heatmap.append({"sector": sector, "average_change": average_change})
    return heatmap